version: '3.8'

services:
  plausible:
    image: ghcr.io/plausible/community-edition:v2.1.3
    container_name: plausible
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_events_db
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      BASE_URL: ${BASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      TOTP_VAULT_KEY: ${TOTP_VAULT_KEY}

      # Postgres (shared)
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}

      # ClickHouse (local para eventos)
      CLICKHOUSE_DATABASE_URL: http://plausible_events_db:8123/plausible_events_db

      # Disable registration (remova para permitir novos usu√°rios)
      DISABLE_REGISTRATION: ${DISABLE_REGISTRATION:-true}
    deploy:
      resources:
        limits:
          memory: 512M

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    container_name: plausible_events_db
    restart: unless-stopped
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  event-data:
    name: plausible-event-data
  event-logs:
    name: plausible-event-logs
