services:
  plausible:
    image: ghcr.io/plausible/community-edition:v3.2.0
    container_name: plausible
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      plausible_events_db:
        condition: service_healthy
    networks:
      - default
      - shared-network
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      BASE_URL: ${BASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      TOTP_VAULT_KEY: ${TOTP_VAULT_KEY}

      # Postgres (shared)
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}

      # ClickHouse (local para eventos)
      CLICKHOUSE_DATABASE_URL: http://plausible_events_db:8123/plausible_events_db

      # Disable registration
      DISABLE_REGISTRATION: ${DISABLE_REGISTRATION:-true}
    deploy:
      resources:
        limits:
          memory: 1G

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.11.1.2557-alpine
    container_name: plausible_events_db
    restart: unless-stopped
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
      - ./clickhouse/ipv4-only.xml:/etc/clickhouse-server/config.d/ipv4-only.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  event-data:
    name: plausible-event-data
  event-logs:
    name: plausible-event-logs

networks:
  shared-network:
    external: true
    name: shared-network
