---
- Aplicações:
    - Zeroslides:
        icon: mdi-presentation
        href: https://zeroslides.melomario.com
        description: Apresentações em Elixir

    - Site Pessoal:
        icon: mdi-web
        href: https://mariomelo.com
        description: Blog pessoal

- Analytics & Monitoring:
    - Plausible:
        icon: plausible
        href: https://analytics.mariomelo.com
        description: Web analytics
        container: plausible

- Infraestrutura:
    - Postgres Compartilhado:
        icon: postgresql
        description: Banco de dados compartilhado
        container: shared-postgres

    - ClickHouse:
        icon: si-clickhouse
        description: Eventos do Plausible
        container: plausible_events_db
