---
title: Servidor Melomario
background:
  image: https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920
  blur: sm
  saturate: 50
  brightness: 50
theme: dark
color: slate

layout:
  - Aplicações:
      style: row
      columns: 3
  - Analytics & Monitoring:
      style: row
      columns: 3
  - Infraestrutura:
      style: row
      columns: 3

providers:
  docker:
    socket: /var/run/docker.sock
